### ISSUE TITLE
Array become `undefined` when passed through pug mixin within svelte pug template.

### ISSUE THREAD

**Issue by singuyen1** [sveltejs/svelte-preprocess#295]
**Describe the bug**
Unable to pass an array to a pug mixin within svelte template.

**To Reproduce**
```
<script>
  $: posts = ['post 1', 'post 2']
</script>

<template lang="pug">
  mixin listItems(posts)
    ul
      each val, index in posts
        li=val

  +listItems(['post 1', 'post 2']) 
  // Print out: <li>post 1</li><li>post 2</li> - Correct
  +listItems({posts})
  // Empty - Bug? as posts now is undefined
</template>
```

- `svelte-preprocess` 4.6.0
- Rollup

**Comment by singuyen1** [comment]
Hi, Is there anyone to look into this? Thanks.

**Comment by kaisermann** [comment]
Hey, @singuyen1 👋  I'm not sure if this scenario should (or could) be supported. If I'm not mistaken, you want to pass a runtime variable to a pug mixin. Unfortunately, that is not possible. The first example works because you're passing a constant array at build-time.

However, you can do something similar with the `+each()` mixin:

```svelte
<script>
  $: posts = ["post 1", "post 2"];
</script>

<template lang="pug">
	+each('posts as post')
		ul
			li="{post}"
</template>
```

There are also some other mixins, check them [here](https://github.com/sveltejs/svelte-preprocess/blob/main/docs/preprocessing.md#pug)

**Comment by singuyen1** [comment]
> Hey, @singuyen1 👋 I'm not sure if this scenario should (or could) be supported. If I'm not mistaken, you want to pass a runtime variable to a pug mixin. Unfortunately, that is not possible. The first example works because you're passing a constant array at build-time.
> 
> However, you can do something similar with the `+each()` mixin:
> 
> ```svelte
> <script>
>   $: posts = ["post 1", "post 2"];
> </script>
> 
> <template lang="pug">
> 	+each('posts as post')
> 		ul
> 			li="{post}"
> </template>
> ```
> 
> There are also some other mixins, check them [here](https://github.com/sveltejs/svelte-preprocess/blob/main/docs/preprocessing.md#pug)

Thanks, that's correct, passing a runtime variable to a pug mixin is impossible. However, I also found that we can do that if using 'https://www.npmjs.com/package/rollup-plugin-pug' and render mixin with` {@html pugMixin() }` would work well.
