### ISSUE TITLE
Having the option to set a default lang for the `style` and `script` tags

### ISSUE THREAD

**Issue by smithliam** [sveltejs/svelte-preprocess#550]
Hi
I didn't find anything related to this in the docs so🤷‍♂️

### **Is your feature request related to a problem? Please describe.**
I don't want to write `lang="postcss"` every single time I want to use a style tag.

### **Describe the solution you'd like**
Having options like this:

```js
preprocess({
  styleTagDefaultLang: 'postcss',
  scriptTagDefaultLang: 'typescript',
  templateTagDefaultLang: 'pug',
})
```

### **Describe alternatives you've considered**
_

### **How important is this feature to you?**
It is so annoying, I use postcss because I use Tailwindcss, so it's necessary for me to add this lang attr. These days everyone uses Tailwind, so it will be awesome for everyone to have the option...

### **Additional context**
Please and thank you.

**Comment by kaisermann** [comment]
Hey @smithliam 👋  We had this functionality in the past, and it's an enormous can of worms for tooling. It's really hard for, i.e, the Svelte VS Code extension to know how to parse your tags. I can see how it can be a bit annoying to add the `lang` attribute to your tags when you're coding a project from scratch, but I'm afraid we won't reconsider adding this again.

You're free, however, to write your own postcss preprocessor or use something like: https://www.npmjs.com/package/svelte-preprocess-postcss

> These days everyone uses Tailwind, so it will be awesome for everyone to have the option...

I'm afraid this is only an assumption.

**Comment by bxt** [comment]
I got syntax errors in my project because I forgot to set `lang="ts"` on some of my `<script>` tags. This was rather unexpected. So I wanted to have all script tags use TypeScript by default. This feature was removed by Svelte, however, what I ended up doing instead is configuring the eslint config with the [rule `svelte/block-lang`](https://sveltejs.github.io/eslint-plugin-svelte/rules/block-lang/) to add lang attributes by default with the correct values. This also works for style tags and postcss. So I would suggest adding something like this to your `eslint.config.js`:

```ts
import { defineConfig } from "eslint/config";

export default defineConfig(
  // ...
  {
    rules: {
      // Add this:
      "svelte/block-lang": ["error", { script: "ts", style: "postcss" }],
    },
  },
);
```

Of course this still means you'll have `lang="postcss"` on all blocks, but at least it's consistent and done automatically.
