### ISSUE TITLE
Specifying default <script> language

### ISSUE THREAD

**Issue by JorensM** [sveltejs/svelte-preprocess#631]
**Is your feature request related to a problem? Please describe.**
Problem is that I have to type out `<script lang="ts">` for each component instead of just `<script>`, even though my project consists of exclusively TypeScript files.

**Describe the solution you'd like**
I believe this was a feature in earlier versions, but I'd like a configuration option that would allow you to specify the default language for `<script>` tags so you don't have to explicitly specify it each time.

**How important is this feature to you?**
Not too important, just a minor inconvenience.

**Comment by dummdidumm** [comment]
We did this a long time ago but it turned out to be a mistake:
- all tooling needs to be aware of the default language some way or the other, leading to either many duplicate definitions, or hacks to know the value
- syntax highlighting of TS and JS files is slightly different, and editors like VS Code pick the syntax highlighting based on tokens (in this case looking for `lang="ts"`). If there's a default language, then that would no longer be possible
- in Svelte 5, `lang="ts"` is also used by the compiler itself to know whether or not the language is TS

Therefore closing.
