### ISSUE TITLE
svelte-preprocess 6.x makes `svelte-check` gives non warnings on svelte 4 projects

### ISSUE THREAD

**Issue by farfromrefug** [sveltejs/svelte-preprocess#663]
**Describe the bug**
I am using svelte-check/svelte-preprocess on svete 4 projects (nativescript/svelte).
Until now i was using svelte-preprocess `5.1.4` and everything was working perfectly.
Now if i update `svelte-preprocess` to 6.x then svelte-check starts reporting warnings when there are not (not warned in vscode)

Not sure if it is related or not but we cant use `verbatimModuleSyntax:true` in Nativescript projects. The reason is that native APIs do use global enums which are forbidden when you have `verbatimModuleSyntax:true`

most of those warnings are related to imports made inside `context="module"` scripts.

Warns look like this :
**Logs**

```
/home/mguillon/dev/nativescript/com.akylas.documentscanner/tools/app/components/IconButton.svelte:59:45
Warn: 'fonts' is not defined (svelte)
    function onCanvasDraw({ canvas, object }: { canvas: Canvas; object: CanvasView }) {
        const theFontFamily = fontFamily || $fonts.mdi;
        let iconPaint = iconPaints[theFontFamily];
```

**To Reproduce**
I dont have a small repo. This is the repo i test it on https://github.com/Akylas/OSS-DocumentScanner
**Expected behavior**
I expect same svelte-check result (green, no warning) with `svelte-preprocess` 6.x and 5.x 

**Information about your project:**

- Non browser project (nativescript/svelte)

- Ubuntu 22.04

- `svelte-preprocess` 6.0.3

- Using webpack

**Additional context**
`svelte-check` 4.1.1

**Comment by dummdidumm** [comment]
You get these warnings because after preprocessing the imports that appear unused (TS can't see template usages) are removed. The black-magic typescript preprocessor that made this possible previously was removed in favor of requiring the verbatimModuleSyntax. Also see the migration guide: https://github.com/sveltejs/svelte-preprocess/blob/main/docs/migration-guide.md#from-v5-to-v6

AFAIK global enums have nothing to do with verbatimModuleSyntax so I'm not sure what you mean by that. Can you give an example?

**Comment by farfromrefug** [comment]
@dummdidumm ok i figured it was that option.
When using `verbatimModuleSyntax:true`, this is the kind of error i get:
![image](https://github.com/user-attachments/assets/8b7183a8-6249-40af-a069-8e22dfed6f38)
The enum being globally declared like this:
```ts
declare const enum UIModalPresentationStyle {

	FullScreen = 0,

	PageSheet = 1,

	FormSheet = 2,

	CurrentContext = 3,

	Custom = 4,

	OverFullScreen = 5,

	OverCurrentContext = 6,

	Popover = 7,

	BlurOverFullScreen = 8,

	None = -1,

	Automatic = -2
}
And in the near future there is now way for us to not use those enums from the global scope
```

**Comment by dummdidumm** [comment]
I see - are you using those global enums in Svelte files, too, or just outside? I'm asking because the preprocessor itself wouldn't know how to transpile those - so are you running a TS processor on the compiled output (i.e. is the webpack config setup that way)?

With enough config tweaking there likely is a way to get it to work:
- don't use `verbatimModuleSyntax` in your tsconfig
- add `verbatimModuleSyntax` to the svelte-preprocessor via the inline tsconfig option
- make sure to import types using the `type` import syntax. I'm not sure what VS Code would do if you don't have this option set (i.e. if it's doing it automatically, if not that's probably annoying)

Does that help?

**Comment by farfromrefug** [comment]
@dummdidumm indeed your trick worked! Awesome thanks a lot
